# Generated by Django 4.2.9 on 2024-06-03 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="postModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Post Title")),
                ("content", models.TextField(verbose_name="Post Content")),
                ("creation_date", models.DateTimeField(editable=False)),
                ("modify_date", models.DateTimeField()),
                (
                    "ulink",
                    models.SlugField(
                        editable=False, unique=True, verbose_name="Unique Link ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("d", "Draft"), ("p", "Publish")],
                        default="d",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
