# Generated by Django 4.2.9 on 2024-06-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_postmodel_creation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="postmodel", name="user",),
    ]
