# Generated by Django 4.2.9 on 2024-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_postmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(blank=True, default="blank.png", upload_to=""),
        ),
    ]
