# Generated by Django 4.2.9 on 2024-06-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_postmodel_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="postmodel", name="author",),
    ]
