# Generated by Django 4.2.9 on 2024-06-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0006_remove_postmodel_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="author",
            field=models.ForeignKey(
                default=None,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
