# Generated by Django 4.2.9 on 2024-06-04 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("User", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="middlename",),
        migrations.AddField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(blank=True, max_length=35, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=200, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
