# Generated by Django 4.2.9 on 2024-06-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_remove_userprofile_middlename_userprofile_lastname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="ProfilePic", new_name="pic",
        ),
    ]
