# Generated by Django 4.2.9 on 2024-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_rename_profilepic_userprofile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email ID"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.SlugField(
                blank=True, editable=False, unique=True, verbose_name="Unique User Id"
            ),
        ),
    ]
