# Generated by Django 4.2.9 on 2024-06-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_userprofile_email_userprofile_uuid"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="uuid",),
    ]
