# Generated by Django 4.2.9 on 2024-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0008_alter_userprofile_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="First Name"
            ),
        ),
    ]
