# Generated by Django 4.2.9 on 2024-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0011_remove_userprofile_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.SlugField(
                blank=True, editable=False, unique=True, verbose_name="Unique User Id"
            ),
        ),
    ]
