# Generated by Django 4.2.9 on 2024-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0012_userprofile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pic",
            field=models.ImageField(
                blank=True,
                default="blank.png",
                upload_to="",
                verbose_name="Profile Picture",
            ),
        ),
    ]
